
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(394, 494)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(394, 494))
        MainWindow.setMaximumSize(QtCore.QSize(394, 494))
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(2, 7, 390, 84))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outputLabel.setLineWidth(3)
        self.outputLabel.setMidLineWidth(1)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget, clicked=self.percent_it)
        self.percentButton.setGeometry(QtCore.QRect(10, 100, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.percentButton.setFont(font)
        self.percentButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.percentButton.setObjectName("percentButton")
        self.cButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("C"))
        self.cButton.setGeometry(QtCore.QRect(110, 100, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.cButton.setFont(font)
        self.cButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cButton.setObjectName("cButton")
        self.delButton = QtWidgets.QPushButton(self.centralwidget, clicked=self.remove_it)
        self.delButton.setEnabled(True)
        self.delButton.setGeometry(QtCore.QRect(210, 100, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(22)
        self.delButton.setFont(font)
        self.delButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delButton.setStyleSheet("")
        self.delButton.setObjectName("delButton")
        self.divButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("/"))
        self.divButton.setGeometry(QtCore.QRect(310, 100, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.divButton.setFont(font)
        self.divButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.divButton.setObjectName("divButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("9"))
        self.nineButton.setGeometry(QtCore.QRect(210, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.nineButton.setFont(font)
        self.nineButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nineButton.setObjectName("nineButton")
        self.mulButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("*"))
        self.mulButton.setGeometry(QtCore.QRect(310, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.mulButton.setFont(font)
        self.mulButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mulButton.setObjectName("mulButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.sevenButton.setFont(font)
        self.sevenButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sevenButton.setObjectName("sevenButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("8"))
        self.eightButton.setGeometry(QtCore.QRect(110, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.eightButton.setFont(font)
        self.eightButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eightButton.setObjectName("eightButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(210, 240, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.sixButton.setFont(font)
        self.sixButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sixButton.setObjectName("sixButton")
        self.subButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("-"))
        self.subButton.setGeometry(QtCore.QRect(310, 240, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.subButton.setFont(font)
        self.subButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.subButton.setObjectName("subButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 240, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.fourButton.setFont(font)
        self.fourButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fourButton.setObjectName("fourButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("5"))
        self.fiveButton.setGeometry(QtCore.QRect(110, 240, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.fiveButton.setFont(font)
        self.fiveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fiveButton.setObjectName("fiveButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 310, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.oneButton.setFont(font)
        self.oneButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.oneButton.setObjectName("oneButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("+"))
        self.addButton.setGeometry(QtCore.QRect(310, 310, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.addButton.setFont(font)
        self.addButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addButton.setObjectName("addButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("3"))
        self.threeButton.setGeometry(QtCore.QRect(210, 310, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.threeButton.setFont(font)
        self.threeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.threeButton.setObjectName("threeButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("2"))
        self.twoButton.setGeometry(QtCore.QRect(110, 310, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.twoButton.setFont(font)
        self.twoButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.twoButton.setObjectName("twoButton")
        self.equalsButton = QtWidgets.QPushButton(self.centralwidget, clicked=self.calculate_it)
        self.equalsButton.setGeometry(QtCore.QRect(310, 390, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.equalsButton.setFont(font)
        self.equalsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.equalsButton.setObjectName("equalsButton")
        self.plusminusButton = QtWidgets.QPushButton(self.centralwidget, clicked=self.plus_minus_it)
        self.plusminusButton.setGeometry(QtCore.QRect(10, 390, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.plusminusButton.setFont(font)
        self.plusminusButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plusminusButton.setObjectName("plusminusButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(110, 390, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.zeroButton.setFont(font)
        self.zeroButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zeroButton.setObjectName("zeroButton")
        self.dotButton = QtWidgets.QPushButton(self.centralwidget, clicked=self.dot_it)
        self.dotButton.setGeometry(QtCore.QRect(210, 390, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        self.dotButton.setFont(font)
        self.dotButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dotButton.setObjectName("dotButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 394, 21))
        self.menubar.setObjectName("menubar")
        self.menuCalculator = QtWidgets.QMenu(self.menubar)
        self.menuCalculator.setObjectName("menuCalculator")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCalculator.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator -by TheLegitProgrammer"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.delButton.setText(_translate("MainWindow", "<<"))
        self.divButton.setText(_translate("MainWindow", "/"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.mulButton.setText(_translate("MainWindow", "x"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.subButton.setText(_translate("MainWindow", "-"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.addButton.setText(_translate("MainWindow", "+"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.equalsButton.setText(_translate("MainWindow", "="))
        self.plusminusButton.setText(_translate("MainWindow", "+/-"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.dotButton.setText(_translate("MainWindow", "."))
        self.menuCalculator.setTitle(_translate("MainWindow", "Calculator"))

    def percent_it(self):
        screen = self.outputLabel.text()
        self.outputLabel.setText(f"{float(screen)/100}")

    def calculate_it(self):
        screen = self.outputLabel.text()
        try:
            answer = eval(screen)
            self.outputLabel.setText(f"{answer}")
        except:
            self.outputLabel.setText("Error")

    def plus_minus_it(self):
        screen = self.outputLabel.text()
        if "-" in screen:
            self.outputLabel.setText(screen.replace("-",""))
        else:
            self.outputLabel.setText(f"-{screen}")

    def remove_it(self):
        screen = self.outputLabel.text()
        screen = screen[:-1]
        self.outputLabel.setText(f"{screen}")

    def dot_it(self):
        screen = self.outputLabel.text()
        if "." in screen:
            pass
        else:
            self.outputLabel.setText(f"{screen}.")

    def press_it(self, pressed):
        if pressed == 'C':
            self.outputLabel.setText("0")
        else:
            if self.outputLabel.text() == "0":
                self.outputLabel.setText("")
            self.outputLabel.setText(f"{self.outputLabel.text()}{pressed}")
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())